### ISSUE TITLE
Feature Request: Difference in PCs and GMs  sets of damage buttons

### ISSUE THREAD

**Issue by apoapostolov** [MrVauxs/PF2e-Target-Damage#1]
Option (off by default if desired) to, if the attack had a selected target, hide the standard set of damage buttons for GMs and only see the damage button rows per target. If the attack had no target, show the default set of damage buttons as normal. 

This cuts the height of the damage chat message for GMs by removing the options they would normally not use since they would focus on the targets.

**Comment by MrVauxs** [comment]
Implemented in [1.1.0](https://github.com/MrVauxs/PF2e-Target-Damage/releases/tag/1.1.0)
