### ISSUE TITLE
Uncaught exception: null reference when calling 'isOwner'

### ISSUE THREAD

**Issue by KSops** [MrVauxs/PF2e-Target-Damage#11]
version 1.3.3

`if (!(await fromUuid(target.uuid)).isOwner) innerHtml.attr('data-visibility', 'gm');`

I guess the code is assuming `fromUuid` will always return a non-null value.

**Comment by MrVauxs** [comment]
I don't get this, I need more info as to what you are experiencing. What is happening? What are you trying to do?

**Comment by KSops** [comment]
There's nothing in particular I'm trying to do, but there's an error that's passively showing up in our play instance in console. It's an uncaught exception that gets thrown at the line indicated in the ticket. Not sure what impact it could be having in our session.

**Comment by MrVauxs** [comment]
What version of Foundry and Pf2e system are you on? And please send me an
image of the error.

pon., 19 gru 2022, 00:15 użytkownik Kyle Sakai ***@***.***>
napisał:

**Comment by KSops** [comment]
Foundry: 10.291
PF2e: 4.5.0

![Screenshot (330)](https://user-images.githubusercontent.com/13683351/208324910-5be34fff-d13f-44ac-a371-f8154129fa2b.png)

**Comment by KSops** [comment]
I suspect what's happening is that if there are tokens that no longer exist, but chat messages are being rendered that reference said actors, then there will be a referencing issue. So there should be a null check issue on locating the target.

e.g.
```
{
    "id": "GcdyZcCkLMYD3LKk",
    "name": "Clay Archer Captain 12",
    "uuid": "Scene.DMYiqONrcXeiADUu.Token.GcdyZcCkLMYD3LKk",
    "img": "tokenizer/npc-images/archer_copy_.Token.webp?1669683049536",
    "hasPlayerOwner": false,
    "playersCanSeeName": true
}
```

This is a "target", but there isn't a corresponding token afaik since our GM deletes enemy tokens when we're done combat. When I load the browser session, such errors are thrown because it's rendering chat entries from previous combat.
