### ISSUE TITLE
Persistant damage button double issue

### ISSUE THREAD

**Issue by uniwars** [MrVauxs/PF2e-Target-Damage#14]
Hi, with Pf2e system last update, same for persistant damage and target damage I got this :

- The "Apply persistant damage" button in the "target" are of the card doesn't add the persistant to the target but to the selected token like the normal button would do.

- After enabling the setting to hide standard system buttons the button to add persistant damage from target damage disappeared and even after unchecking the option it didn't came back. In fact after F5 it fixes the old chat card.

**Comment by MrVauxs** [comment]
I cannot replicate this, can you give an example of how this was done?

**Comment by MrVauxs** [comment]
This may also be fixed in 1.5.1

**Comment by uniwars** [comment]
it seems to be fixed, thank you !
