### ISSUE TITLE
Persistant damage applied to both selected token and target

### ISSUE THREAD

**Issue by uniwars** [MrVauxs/PF2e-Target-Damage#17]
Hi, I have an issue that appeared when using the "Apply persistant damage" button that adds the damage to both selected token and target.

Tested with :

- System 4.6.3
- Persistant damage 0.11.2
- Target damage 1.5.3
- Option to hide standard damage button ON
- No other module activated

**Comment by uniwars** [comment]
After a reboot I am not able to reproduce the issue, so it's all good I presume

**Comment by MrVauxs** [comment]
Fixed in [1.5.4](https://github.com/MrVauxs/PF2e-Target-Damage/releases/tag/1.5.4)
