### ISSUE TITLE
Double/half damage and heal button doesn't work

### ISSUE THREAD

**Issue by uniwars** [MrVauxs/PF2e-Target-Damage#18]
Hi, it seems that the double/half damage and the heal button only do normal damage to target (heal deals damage).

Tested with :

System 4.6.3
Target damage 1.5.3
Option to hide standard damage button ON
No other module activated

**Comment by MrVauxs** [comment]
Fixed in [1.5.4](https://github.com/MrVauxs/PF2e-Target-Damage/releases/tag/1.5.4)
