### ISSUE TITLE
[Persistent Damage integration] Recovery button hidden inside collapsible field

### ISSUE THREAD

**Issue by weepingminotaur** [MrVauxs/PF2e-Target-Damage#19]
Occurs when you don't have Hide Collapsible Buttons enabled in Target Damage. The Recovery button (from the Persistent Damage module) is only visible when you click the — button to expand the field. If you do have Hide Collapsible Buttons enabled, the button is visible by default.

**Comment by MrVauxs** [comment]
Can't reproduce, everything shows up correctly on my end.

**Comment by uniwars** [comment]
I made some tests, the first recovery button appeared normally, but the second was in the collapsed buttons
![image](https://user-images.githubusercontent.com/65986545/210994661-5ea5018e-e473-4933-9a59-248a4f033991.png)
![image](https://user-images.githubusercontent.com/65986545/210994865-223b665e-0d86-4e63-8146-6f38fc94ff29.png)
