### ISSUE TITLE
Item Consumable roll for healing/damage create unexpected error when clicking damage or heal

### ISSUE THREAD

**Issue by Fyrexian** [MrVauxs/PF2e-Target-Damage#22]
V10.291 
PF2e 4.6.4

https://user-images.githubusercontent.com/47077661/211208564-91bfde51-44ba-4d4f-8a99-a63a3f07d490.mp4

**Comment by MrVauxs** [comment]
I don't think this is a Target Damage issue as much as a PF2e issue. Reimport the elixir and try again.
