### ISSUE TITLE
Compatibility issues with chat portrait

### ISSUE THREAD

**Issue by Janonas** [MrVauxs/PF2e-Target-Damage#27]
The module "chat portrait" seems to confuse the image of the cross on the double damadge button as an additional portrait. This only happes while its enabled alongside this module 
![the cross issue](https://user-images.githubusercontent.com/38334265/212555721-31c1d893-4eff-41cc-97f0-d1762af61b3e.jpg)

**Comment by Janonas** [comment]
Also apologies for posting too much about the problems i notice, im not trying to do it out of malice, but i wish to report any bugs i find

**Comment by MrVauxs** [comment]
I don't believe this is a PF2e Target Damage issue but a Chat Portrait one, especially with the fact it's removing the system buttons icon, not one from the module.

**Comment by Janonas** [comment]
Oh, it seems so. Ive just tested the portrait module by itself on a pf2e game and the issue happens. ill notify them. Sorry for the confusion
