### ISSUE TITLE
Feature Suggestion: Target buttons

### ISSUE THREAD

**Issue by roguedevjake** [MrVauxs/PF2e-Target-Damage#3]
Putting a target button next to each name/section could be useful. The code for doing so can be stolen from the persistent damage module.

**Comment by MrVauxs** [comment]
While I would gladly add that, Persistent Damage doesn't have that button anymore and relies on PF2e system's "hover over message and it auto-selects the token" function.
Which I don't know how to replicate, yet.

**Comment by MrVauxs** [comment]
Implemented in next release.
