### ISSUE TITLE
UI Bug

### ISSUE THREAD

**Issue by Tondrin** [MrVauxs/PF2e-Target-Damage#41]
With the mod enabled, targeted rolls cause the entire UI to scroll up past the screen, only affecting players, not the DM. Fixed with a refresh but repeating

![It does this](https://user-images.githubusercontent.com/86505387/222950079-d7685c5e-17a9-4797-80fd-41b078a22d30.png)

**Comment by MrVauxs** [comment]
It has already been fixed in [2.4.3](https://github.com/MrVauxs/PF2e-Target-Damage/releases/tag/2.4.3)
