### ISSUE TITLE
Target is not 

### ISSUE THREAD

**Issue by thwegg** [MrVauxs/PF2e-Target-Damage#45]
I'm getting a weird error when one of my players uses a spell, Divine Lance, regardless of what type of damage he chooses, when I attempt to apply the damage, it says for example unnaffected by chaotic: -5. The monsters in question do not have any immunities and regardless of the damage type it gives that error, and I have to apply that damage manually. 
![Screenshot 2023-02-25 220102](https://user-images.githubusercontent.com/59631153/224830815-1b5c55a7-02d6-4064-bf13-2d6110136b72.png)
![Screenshot 2023-03-13 165916](https://user-images.githubusercontent.com/59631153/224831119-a85a9031-8570-4901-b0cf-650b52f32d88.png)

**Comment by MrVauxs** [comment]
Giant Scorpion and Slurk are both Neutral creatures, who do not take ANY alignment damage.
This is completely unrelated to PF2e Target Damage, what you are witnessing is PF2e system's damage automation.

If you want to homebrew such damage types to deal damage, you can use [PF2e Alignment Damage](https://foundryvtt.com/packages/pf2e-alignment-damage)
