### ISSUE TITLE
Specific target damage buttons fails to damage/heal/etc. target

### ISSUE THREAD

**Issue by RikerW** [MrVauxs/PF2e-Target-Damage#48]
```js
Uncaught (in promise) ReferenceError: undefined. extractEphemeralEffects is not defined
[Detected 1 package: pf2e-target-damage]
    at applyDamage (target-damage.js:312:7)
    at HTMLButtonElement.<anonymous> (target-damage.js:603:7)
    at HTMLButtonElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)
```

Looks like there's missing library or something somewhere, unless that's something deprecated/removed from foundry itself. Tested using Target Damage 2.4.10, and PF2E 4.10.4.

Relevant lines:
https://github.com/MrVauxs/PF2e-Target-Damage/blob/3c386c2cdc09b1c2f6cae13ffd4d904803efd2ce/module/target-damage.js#L312-L320

Looks like 2.4.10 introduced this bug, see [here](https://github.com/MrVauxs/PF2e-Target-Damage/commit/3c386c2cdc09b1c2f6cae13ffd4d904803efd2ce#diff-26ab6c3512d3b410cd31e0980b226b70294a94a0db4468a5922fbb806cf66d1aR312). Guess I chose the wrong time to update!

**Comment by MrVauxs** [comment]
Hopefully resolved in [2.4.11](https://github.com/MrVauxs/PF2e-Target-Damage/releases/tag/2.4.11), busy with a Lancer game.
