### ISSUE TITLE
Select target/show target only works on the first one

### ISSUE THREAD

**Issue by Cosmic-Lattee** [MrVauxs/PF2e-Target-Damage#5]
So when you hover over the first goblin here it shows you the target like expected. 
![image](https://user-images.githubusercontent.com/24766235/195726452-239b549c-de97-476f-9edb-d715505d3ee1.png)

but when you select another goblin here it doesn't seem to do anything. Not sure if I am doing something wrong or if something isn't working as intended.
![image](https://user-images.githubusercontent.com/24766235/195726526-17fb33d7-3caa-46f0-874e-6031affbd748.png)

Tested with no other modules going
![image](https://user-images.githubusercontent.com/24766235/195726607-0a35612a-4ff9-45e3-948e-fd156f2e3e48.png)

**Comment by MrVauxs** [comment]
Fixed in the next update.
