### ISSUE TITLE
Compatibility with PF2e Workbench Mystified Spells

### ISSUE THREAD

**Issue by HydrallUrakan** [MrVauxs/PF2e-Target-Damage#51]
PF2e workbench has an option to mystify spells cast by NPCs, producing a message with some details but not the full text of the spell - useful for running Recognize Spell RAW. The second message contains a button for rolling the required saves. However, this is a separate message from the original spell message, and so naturally doesn't apply those save results to the target damage section of the spell card. 

Is there any way that these could be linked? It's not the biggest hassle, but it would be nice to have it work together if possible.

![image](https://user-images.githubusercontent.com/94702225/233793477-13cb9cf0-14e6-4d3e-807d-f376329b01e6.png)

**Comment by MrVauxs** [comment]
This will be done, or at least mitigated as a part of #38.
