### ISSUE TITLE
Damage Card in Conflict with PF2e Workbench

### ISSUE THREAD

**Issue by Sildamet** [MrVauxs/PF2e-Target-Damage#56]
Howdy folks. So I'm having an issue when using PF2e Target Damage and PF2e Workbench together, that after I rolled saving throws and damages, the moment I apply the damage to a target the "card" becomes just a regular number and the damage can't be applied to any other target.
Example: This card
![image](https://github.com/MrVauxs/PF2e-Target-Damage/assets/74163724/c87f5de4-f2bc-4bfd-934b-505941b7ce26)

Turns into this card
![image](https://github.com/MrVauxs/PF2e-Target-Damage/assets/74163724/80c1132d-79ad-4318-a3c7-7880a576a497)

I wasn't sure to whom I should report the issue, so I decided to report to both creators. :) Thank you for your attention!

**Comment by MrVauxs** [comment]
Have you confirmed this only happens when those two mods are enabled?
Also, are you on the latest version of PF2e Workbench and PF2e Target Damage?

**Comment by MrVauxs** [comment]
Confirmed to be Workbench issue.
