### ISSUE TITLE
Console Error when mousing over target names in chat

### ISSUE THREAD

**Issue by ottyn** [MrVauxs/PF2e-Target-Damage#57]
Foundry v11.304
PF2e v5.1.0
Target Damage v2.4.13

Getting the following error in the console when you mouse over the target names in the chat card.  Doesn't seem to effect the damage or save buttons.  Everything still works correctly in game.

![Target-Damage-Error](https://github.com/MrVauxs/PF2e-Target-Damage/assets/97130150/979f0654-aa26-442e-9f58-f20c1a3b83d6)

**Comment by MrVauxs** [comment]
~~PF2e System~~ Foundry VTT Issue. https://github.com/foundryvtt/foundryvtt/issues/9667
