### ISSUE TITLE
Discord FoundryVTT Announcement 404 ERROR

### ISSUE THREAD

**Issue by Maggard** [MrVauxs/PF2e-Target-Damage#6]
Today at 10:36 CST the "PF2e Target Damage - Version 1.3.0" announcement contains the following link:

https://github.com/MrVauxs/PF2e-Target-Damage/blob/main/CHANGELOG.md

Accessing this link leads to the GitHub.com 404 ERROR page.

**Comment by MrVauxs** [comment]
Fixed for future updates.
