### ISSUE TITLE
Damage hints for saving throw degree of success are only shown on second damage roll

### ISSUE THREAD

**Issue by SchnozzleCat** [MrVauxs/PF2e-Target-Damage#60]
If you target creatures, roll their saves, and then roll damage, the damage hints (which button is "correct") are not shown. 
If you roll again from the same chat message, they are shown correctly again.

This was tested on Foundry 11.307, PF2E system version 5.3.1, and PF2E Target version 2.4.14 on a fresh world with no other modules except quick insert enabled.

Other users in the discord also have the same issue.

Example:
![image](https://github.com/MrVauxs/PF2e-Target-Damage/assets/67333469/55704b02-d483-40ca-b836-32f8a7d4c852)

**Comment by Khybersghost** [comment]
Can confirm this. 
Foundry 11.307
PF2e 5.3.1

No console errors noted.

**Comment by labrown** [comment]
Also Confirmed:
Foundry 11.307
PF2E 5.3.2
PF2e Target Damage 2.4.14
