### ISSUE TITLE
Discrepancy between Target Damage and System Damage Buttons

### ISSUE THREAD

**Issue by XyrilP** [MrVauxs/PF2e-Target-Damage#65]
As title says, may be incompatible with the healing-received selector overall.
![Screenshot 2023-10-20 003831](https://github.com/MrVauxs/PF2e-Target-Damage/assets/69739925/0abd0166-9b1d-4aab-b09c-ccdd114e4792)
(Healing with Target Damage vs. without it (untargeted).)

**Comment by Aeristoka** [comment]
Have this exact same issue.

Original Application buttons have `class="heal-damage` vs. Target Damage buttons with `class="pf2e-td heal-damage applied"`

It's definitely something with how pf2e is interpreting the Target Damage healing application button.

**Comment by MrVauxs** [comment]
It's not about the classes. It's about having an outdated applyDamageFromMessage function.
Will have to copy paste the system code again so its up to date.

Made an issue in the pf2e system to not have to copy paste code and keep it from going stale.
https://github.com/foundryvtt/pf2e/issues/10927

**Comment by Aeristoka** [comment]
> It's not about the classes. It's about having an outdated applyDamageFromMessage function. Will have to copy paste the system code again so its up to date.
> 
> Made an issue in the pf2e system to not have to copy paste code and keep it from going stale. [foundryvtt/pf2e#10927](https://github.com/foundryvtt/pf2e/issues/10927)

Oh interesting, and a good ask of the pf2e devs!

**Comment by MrVauxs** [comment]
Looks like updating the damage function will need more involvement than a mere copy paste, as that doesn't seem to be doing much in terms of fixing these issues, if not outright breaking stuff.

If anyone wants to look into this, I will gladly merge the PR.

**Comment by SMJL88** [comment]
I'm not sure but would this be what is causing the life oracle curse to not apply the penalty properly properly? The system damage button works properly however the target one does not.

**Comment by MrVauxs** [comment]
> I'm not sure but would this be what is causing the life oracle curse to not apply the penalty properly properly? The system damage button works properly however the target one does not.

Yes
