### ISSUE TITLE
Damage is only applied to selected tokens with 2 new warnings after pf2e 4.3.0 update

### ISSUE THREAD

**Issue by OmerCora** [MrVauxs/PF2e-Target-Damage#8]
Hello!

Sorry if I am missing something,
Target Damage stopped working for me. Currently the damage is always applied to the selected token instead of the target token and it produces 2 warnings every time applyDamage is called, I also noticed trying to hide the Original system dmg buttons stopped working for me.
I believe this began occurring right after yesterday's pf2e system update to 4.3.0. 

Here is how both warnings look like:
![issue1](https://user-images.githubusercontent.com/1075661/198399266-db3103a5-a95f-4ef6-8d5b-458bc14e3fb3.png)

**Comment by MrVauxs** [comment]
Working on fixing it.
