### ISSUE TITLE
Targets is Undefined

### ISSUE THREAD

**Issue by velara** [MrVauxs/PF2e-Target-Damage#9]
I get the following error message whenever I launch my game on the forge with PF2e-Target-Damage enabled. I've disabled all other modules and the error persists. I've not actually used the module yet as this occurred immediately after first install so I can't speak to its impacts on functionality.

![image](https://user-images.githubusercontent.com/74130268/206940312-09da0b40-0035-45ac-8b1d-27ebd6f91033.png)

Foundry V10 build 290
PF2e 4.4.2
PF2e-Target-Damage 1.3.2

**Comment by MrVauxs** [comment]
Please check the following release and see if it works.
https://github.com/MrVauxs/PF2e-Target-Damage/releases/tag/1.3.!3

**Comment by velara** [comment]
It does not 
![image](https://user-images.githubusercontent.com/74130268/207084144-780c6b72-3cca-44c0-9e6b-cce3e629a899.png)

**Comment by MrVauxs** [comment]
I see what's wrong. See [1.3.!4](https://github.com/MrVauxs/PF2e-Target-Damage/releases/tag/1.3.!4)

**Comment by velara** [comment]
Unlike the previous pre-release this one didn't get picked up by forge, and I didn't want to do too much wrangling on my game server. So I loaded up 1.3!4 on my development copy of foundry and the issue seems to be resolved. So unless it is something forge specific you should be good to go.

**Comment by MrVauxs** [comment]
These shouldn't have been picked up by Forge, 1.3.!3 being available on there was a mishap unfortunately.
Still, glad to see it resolved, releasing in a full version.
